### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
Add cache to workflows using actions/setup-node

### CODE REVIEW

**Comment by oscard0m** [comment]
Closing this PR and opened a discussion to setup a plan for doing this: https://github.com/octoherd/octoherd/discussions/27

**Comment by gr2m** [comment]
It was a good PR, I'd have merged it? I'd suggest to re-run the script or re-open the PRs and merge them. At least for the @octoherd org they look good?

**Comment by oscard0m** [comment]
> It was a good PR, I'd have merged it? I'd suggest to re-run the script or re-open the PRs and merge them. At least for the @octoherd org they look good?

I wanted to be kind and discuss it first as it caused problems in other repositories but if you are ok with it I will run it again :).

We should discuss the plan for the already created repositories outside of `octoherd` org. With the GitHub App there we ask to install to users there is a way to trigger a PR right?

**Comment by gr2m** [comment]
> I wanted to be kind and discuss it first as it caused problems in other repositories but if you are ok with it I will run it again

as you are a maintainer of @octoherd it's okay to just run the script here. It's okay if things go a bit wrong here.

I would always discuss it repositories where you are not a maintainer yourself though. And if you want to send multiple PRs with the same change across an organization then I would create a single issue to discuss it, not one issue per repository.

> We should discuss the plan for the already created repositories outside of `octoherd` org. With the GitHub App there we ask to install to users there is a way to trigger a PR right?

Yes we can do that, I've done it in the past. Right now it's a manual process, but it's something I'd like to automate in the future. But as this is not directly related to the scripts themselves but only the CI setup, I don't think we need to send PRs in this case. I'd only do it to help people migrate to new features / versions of @octoherd

**Pull request closed without merging**
